config/routes.rb
Rails.application.routes.draw do


  post 'events/:id/hosts' => 'events#toggle_host'

  # get 'games/show'
  get 'games' => 'games#show'

  delete 'users/:id/:game_id' => 'users#remove_game'

  post 'add_game' => 'games#add_to_user'#, as: "add_game"
  # post 'game_added' => 'games#add_to_user', as: "game_added"

  resources :events

  post 'events/:id' => 'events#going'

  root 'home#home'
  devise_for :users, :controllers => { :sessions => "custom_sessions" }
  resources :users
  get 'locations/new' => 'locations#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/:id' => 'users#show'
  get 'users/index'
  get 'users/:id/edit' => 'users#edit'

  # messaging
  get 'rooms/show'
  get 'chat' => 'rooms#show'


  # TODO: route  chat by id like below
  # get '/rooms/:id' => 'rooms#show'
  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # attr_accessor :profile_img_file_name
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username,
            uniqueness: true ,
            presence: true,
            length: {minimum: 3, maximum: 16}
  validates :zip, presence: true,
            numericality: {only_integer: true}

  has_many :games_users
  has_many :games, through: :games_users

  # has_and_belongs_to_many :events

  has_attached_file :profile_img, :styles => { medium: "300x300#", thumb: "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :profile_img, :content_type => /\Aimage\/.*\Z/

  has_and_belongs_to_many :events, through: :events_users
  has_many :events_users

  geocoded_by :zip
  after_save :geocode
  after_validation :geocode
    STATES = ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"]
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :remove_game]

    def index
      @users = current_user.nearbys(25) || User.near("Miami", 200)
    end
    def show
      @users_games = []
      @games_user_records = GamesUser.where(user_id: current_user)
      @games_user_records.each do |record|
        @users_games << Game.find(record.game_id)
      end
      @users_games
    end


    def edit
    end

    def remove_game
      @games_user_records = GamesUser.where(user_id: current_user).all
      if @user == current_user
        @games_user_records.find_by(game_id: params[:game_id]).delete
      else
        flash[:alert]= "That's not your account..."
      end
      redirect_to @user
    end

    def update
      respond_to do |format|

        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    end
private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :zip, :address, :country, :state, :dob, :fb, :psn, :xbox, :steam, :twitch, :bio, :profile_img)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_for current_user, html: { multipart: true } do |f| %>

  <div class="field">
    <%= f.label :email %> <br />
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :profile_img %> <br />
    <%= f.file_field :profile_img %>
  </div>
  <div class="field">
    <%= f.label :first_name %> <br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %> <br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :dob %> <br />
    <%= f.date_field :dob %>
  </div>
  <div class="field">
    <%= f.label :bio %> <br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :zip %> <br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :country %> <br />
    <%= f.select :country, ["United States"] %>
  </div>
  <div class="field">
    <%= f.label :address %> <br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :state %> <br />
    <%= f.select :state, User::STATES %>
  </div>
  <div class="field">
    <%= f.label :steam %> <br />
    <%= f.text_field :steam %>
  </div>
  <div class="field">
    <%= f.label :xbox %> <br />
    <%= f.text_field :xbox %>
  </div>
  <div class="field">
    <%= f.label :psn %> <br />
    <%= f.text_field :psn %>
  </div>
  <div class="field">
    <%= f.label :twitch %> <br />
    <%= f.text_field :twitch %>
  </div>



  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Local Users</h1>

<% @users.each do |user| %>
  <div class="user">
    <%= image_tag user.profile_img.url(:thumb), alt: "#{user.username} avatar" %>
    <%= link_to  user.username, "users/#{user.id}"%>
  </div>
<% end %>

app/views/users/show.html.erb
<% title "My Profile" %>

<%= @user.username %>
<!-- <img src="<%= @user.profile_img%>" alt="profile pic" /> -->
<%= image_tag  @user.profile_img.url(:medium ) %> <br>
<%= @user.first_name %> <br>
<%= @user.last_name %> <br>
<%= @user.email %> <br>
<%= @user.country %> <br>
<%= @user.zip %> <br>
<%= @user.address %> <br>
<%= @user.state %> <br>
<%= @user.bio %> <br>
<%= @user.dob %> <br>


  Steam Profile URL: <%= link_to @user.steam, "http://steamcommunity.com/id/#{@user.steam}" %> <br>
Xbox Gamer Tag URL:
  <% if @user.xbox %>
    <%=link_to @user.xbox, "https://account.xbox.com/en-US/Profile?gamerTag=#{(@user.xbox).gsub(" ", "+")}" %> <br>
  <% end %>


PlayStation Network URL: <%= link_to @user.psn, "https://my.playstation.com/#{@user.psn}" %> <br>
Twitch Profile URL: <%= link_to @user.twitch, "https://www.twitch.tv/#{@user.twitch}/profile" %> <br>

<% @user.events.each do |event| %>
  <%= event.name %>
  <%= link_to "Event", event_path(event) %>
<% end %>


<% @users_games.each do |game|%>
  <% if @user == current_user %>
    <%= link_to game.title, "#{@user.id}/#{game.id}", method: :delete, data: {confirm: 'Are you sure you want to delete this game?'} %> <br />
  <% else %>
    <%= game.title %> <br />
  <% end %>
<!-- <img src="<%#game.image%>" alt="game logo" width="100px"/> <br> -->
<% end %>


<div>
  <%= link_to 'Nearby Users', users_path%>
</div>

<% if current_user %>
  <% if current_user.id == @user.id %>
    <%= link_to "Edit", edit_user_path(@user) %>
  <% end %>
<% else %>
  <%= flash[:notice] = "Sign in to edit" %>
<% end %>