config/routes.rb
Rails.application.routes.draw do


  post 'events/:id/hosts' => 'events#toggle_host'

  # get 'games/show'
  get 'games' => 'games#show'

  delete 'users/:id/:game_id' => 'users#remove_game'

  post 'add_game' => 'games#add_to_user'#, as: "add_game"
  # post 'game_added' => 'games#add_to_user', as: "game_added"

  resources :events

  post 'events/:id' => 'events#going'

  root 'home#home'
  devise_for :users, :controllers => { :sessions => "custom_sessions" }
  resources :users
  get 'locations/new' => 'locations#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/:id' => 'users#show'
  get 'users/index'
  get 'users/:id/edit' => 'users#edit'

  # messaging
  get 'rooms/show'
  get 'chat' => 'rooms#show'


  # TODO: route  chat by id like below
  # get '/rooms/:id' => 'rooms#show'
  mount ActionCable.server => '/cable'
end

app/models/event.rb
class Event < ApplicationRecord
  has_and_belongs_to_many :users, through: :events_users
  has_and_belongs_to_many :games
  has_many :events_users

  validates :name, presence: true,length: {minimum: 3}
  validates :description, presence: true,length: {maximum: 500}
  validates :date, presence: true
  validates :time, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true, numericality: {only_integer: true}
  validates :country, presence: true

  geocoded_by :zip
  after_save :geocode
  after_validation :geocode

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :set_event, only: [:show, :edit, :update, :delete, :going, :toggle_host, :destroy]
  before_filter :only_host, only: [:edit, :update, :delete, :toggle_host, :destroy]
  before_action :set_user, only: [:toggle_host, :ensure]
  before_action :ensure_host, only: [:toggle_host]


  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
        @event.users << current_user
          if @event.events_users.first.user_id == current_user.id
             @event.events_users.first.update(is_host: true)
          end
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end

  end

  def going
    if @event.users.include?(current_user)
        @event.users.delete(current_user)
    else
      @event.users << current_user
    end
    if @event.events_users.where(is_host: true) == []
        @event.delete
      redirect_to events_path
    else
      redirect_to @event
    end
  end

  def index
    # @events = Event.all
    @events = Event.near([current_user.latitude, current_user.longitude], 300) || Event.near(current_user.city, 300)
  end

  def show
  end

  def destroy
    @event.events_users.where(event_id: @event.id).delete_all
    @event.delete
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  def delete
    @event.events_users.where(event_id: @event.id).delete_all
    @event.delete
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def edit
  end

  def toggle_host
    #check for input
    if @user
      #set user to toggle to input
      new_host = @event.events_users.find_by(user_id: (@user.id))
      if new_host
        if new_host.is_host
          new_host.is_host = false
        else
          new_host.is_host = true
        end
        new_host.save
        if @event.events_users.where(is_host: true) == []
            @event.delete
          redirect_to events_path
        else
          redirect_to @event
        end
      else
        redirect_to @event
        flash[:notice] = "#{@user.username} isn't attending this event"
      end
    else
      redirect_to @event
      flash[:alert] = "You need to specify the user to hostify!"
    end
  end

  def update
  #if current_user is host
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

    private
  def event_params
    params.require(:event).permit(:name, :description, :date, :time, :address, :city, :state, :zip, :country)
  end
  def only_host
    unless @event.events_users.where(is_host: true, user_id: current_user.id).exists?
      redirect_to @event
      flash[:alert] = "You must be a host to do that"

    end
  end
  def ensure_host
    #if there is one host and
    if (@event.events_users.where(is_host: true).length ==1) && (current_user == @user)
      redirect_to @event
      flash[:alert] = "You can't delete the last host"
    end
  end
  def set_event
    @event = Event.find(params[:id])
  end
  def set_user
    @user = User.find_by(username: params[:username])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date %>
    <%= f.date_field :date%>
  <div class="field">
    <%= f.label :time %>
    <%= f.time_field :time %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %>
    <%= f.select :state, ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"] %>
  </div>
  <div class="field">
    <%= f.label :Zipcode %>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :country %> <br />
    <%= f.select :country, ["United States"] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_host_form.html.erb
<%= form_tag("#{@event.id}/hosts", method: "post") do %>
  <%= label_tag(:username, "Username:") %>
  <%= text_field_tag(:username) %>
  <%= submit_tag("Toggle Host") %>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/edit.html.erb
<h1>Edit Event</h1> <br /><br /><br /><br />
<%= render 'form' %>

app/views/events/index.html.erb
<%= link_to "Host an event", new_event_path %>  <br>

<% @events.each do |event| %>
---------------------------------- <br>
  <%= link_to event.name, event_path(event) %> <br />
  <%= event.city %> <%= event.state %>, <%= event.zip %> <br /> <br />

<% end %>

app/views/events/new.html.erb
<h1>New Event</h1> <br /><br /><br />
<%= render 'form' %>

app/views/events/show.html.erb
<% title "Event Information" %>
<h1>Event Information</h1>

<h2>  <%= @event.name %> </h2>
<%= @event.address %> <br />
<%= @event.city %> <br />
<%= @event.state %> <br />
<%= @event.zip %> <br />
Description: <%= @event.description %> <br />
Hosts: <% @event.events_users.where(is_host: true).each do |hosts|%>
  <%= User.find(hosts.user_id).username %>
<% end %>

  <% if @event.users.include?(current_user) %>

    <% if (@event.events_users.where(is_host: true).length ==1) && (@event.events_users.where(is_host: true, user_id: current_user.id).exists?) %>
      <%= button_to "I can't make it", @event, data: {confirm: 'You are the last host, so leaving this event will destroy it. Are you sure you want to leave?'}%>

    <% else %>
      <%= button_to "I can't make it", @event%>

    <% end %>
  <% else %>
    <%= button_to "I'm going", @event%>

  <% end %>


<% if @event.events_users.where(is_host: true, user_id: current_user.id).exists? %>
    <%= button_to "Edit Event", edit_event_path, method: :get %>
    <%=   button_to "Delete Event", @event, method: :delete, data: {confirm: 'Are you sure you want to delete this event?'}%>
    <%= render 'host_form' %>
     <% end %>

     <%= button_to "Events", events_path, method: :get %>