config/routes.rb
Rails.application.routes.draw do


  post 'events/:id/hosts' => 'events#toggle_host'

  # get 'games/show'
  get 'games' => 'games#show'

  delete 'users/:id/:game_id' => 'users#remove_game'

  post 'add_game' => 'games#add_to_user'#, as: "add_game"
  # post 'game_added' => 'games#add_to_user', as: "game_added"

  resources :events

  post 'events/:id' => 'events#going'

  root 'home#home'
  devise_for :users, :controllers => { :sessions => "custom_sessions" }
  resources :users
  get 'locations/new' => 'locations#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'users/:id' => 'users#show'
  get 'users/index'
  get 'users/:id/edit' => 'users#edit'

  # messaging
  get 'rooms/show'
  get 'chat' => 'rooms#show'


  # TODO: route  chat by id like below
  # get '/rooms/:id' => 'rooms#show'
  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- <title>LGN - LocalGamersNetwork</title> -->
    <title><%= content_for?(:title) ? "LGN | #{yield(:title)}" : 'LGN | LocalGamersNetwork' %></title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <!-- Google-Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Lato:400,300,700,900'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Orbitron:400,500,700,900'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Press+Start+2P'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300,700'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,700'
          rel='stylesheet' type='text/css'>
  </head>

  <body>
    <div class="wrapper">

        <nav> <!-- Flex Parent -->
          <ul class="title"> <!-- Flex ^ Child/Parent v -->
            <li id="logo">
              <%= link_to root_path  do %>
                <div class="logo-box">
                  <%#= image_tag "logos/ghost_grn.png", id: "logo" %>
                  <%= image_tag "logos/joystick_solid_blue.png", id: "logo" %>
                </div>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
              <!-- <h4>Local Gaming Network</h4> -->
              <h2>LGN</h2>
              <!-- Local Gaming Network -->
              <% end %>
            </li>
          </ul>
          <ul class="menu">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Games", games_path %></li>
            <li><%= link_to "Events", events_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Chat", chat_path %></li>

            <li><%= link_to "Profile", user_path(current_user) if user_signed_in? %></li>
          </ul>

        </nav>
        <div class="main">

        <!-- TODO: Take links out of here and put them in a header _partial  -->
        <div class="user-auth-bar">
          <ul class="clean-list">
            <li class="notice"><%= notice %></li>
            <li class="alert"><%= alert %></li>
          <% if !user_signed_in? %>
            <li><%= link_to("Sign in", new_user_session_path) %></li><span>or</span>
            <li><%= link_to("Sign up", new_user_registration_path) %></li>
          <% else %>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% end %>
          </ul>
        </div>

        <%= yield %>
      </div>
      <footer>
        <p>jashfjksahfkjeh HEY SOME CONENT HERE</p>
        <p>jashfjksahfkjeh HEY SOME CONENT HERE</p>
      </footer>
    </div>
  </body>
</html>